/**
 * Generated on 2024-05-08T03:54:02.567Z by `yarn makemigrations`
 * The following schema changes were detected:
 * -------------------------------------------
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- Text (8 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * Renamed from /Users/vlad/coding/dance/fm/ForumMagnum/schema/accepted_schema.sql to /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql
 *  2 -- Do not edit this file directly. I 2 -- Do not edit this file directly. I
 *  . nstead, start a server and run "yarn . nstead, start a server and run "yarn
 *  .  makemigrations"                     .  makemigrations"
 *  3 -- as described in the README. This  3 -- as described in the README. This 
 *  . file should nevertheless be checked  . file should nevertheless be checked 
 *  . in to version control.               . in to version control.
 *  4 --                                   4 --
 *  5 -- Overall schema hash: 686739254a73 5 -- Overall schema hash: 87aaf5d4d928
 *  . ddf6ef74c8af507bfdf0                 . 006e4cd2b921c26a2180
 *  6                                      6 
 *  7 -- Accepted on 2024-05-03T19:24:24.0 . 
 *  . 00Z by 20240503T192424.update_notifi . 
 *  . cation_defaults.ts                   . 
 *  8                                      . 
 *  9 -- Extension "btree_gin", hash: 8833 7 -- Extension "btree_gin", hash: 8833
 *  . dd03dc128e186d2c560d248354fb         . dd03dc128e186d2c560d248354fb
 * 10 CREATE EXTENSION IF NOT EXISTS "btre 8 CREATE EXTENSION IF NOT EXISTS "btre
 * .. e_gin" CASCADE;                      . e_gin" CASCADE;
 * 11                                      9 
 * 
 * 
 * -------------------------------------------
 * (run `git diff --no-index schema/accepted_schema.sql schema/schema_to_accept.sql` to see this more clearly)
 *
 * - [ ] Write a migration to represent these changes
 * - [ ] Rename this file to something more readable
 * - [ ] Uncomment `acceptsSchemaHash` below
 * - [ ] Run `yarn acceptmigrations` to update the accepted schema hash (running makemigrations again will also do this)
 */
export const acceptsSchemaHash = "87aaf5d4d928006e4cd2b921c26a2180";

export const up = async ({db}: MigrationContext) => {
  // noop merge migration
}

export const down = async ({db}: MigrationContext) => {
  // TODO, not required
}
