/**
 * Generated on 2024-05-03T19:24:24.108Z by `yarn makemigrations`
 * The following schema changes were detected:
 * -------------------------------------------
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 1/4 --- Text (8 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * Renamed from /Users/vlad/coding/dance/fm/ForumMagnum/schema/accepted_schema.sql to /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql
 *  2 -- Do not edit this file directly. I 2 -- Do not edit this file directly. I
 *  . nstead, start a server and run "yarn . nstead, start a server and run "yarn
 *  .  makemigrations"                     .  makemigrations"
 *  3 -- as described in the README. This  3 -- as described in the README. This 
 *  . file should nevertheless be checked  . file should nevertheless be checked 
 *  . in to version control.               . in to version control.
 *  4 --                                   4 --
 *  5 -- Overall schema hash: 501675659a25 5 -- Overall schema hash: 686739254a73
 *  . e292d63216f08d78c445                 . ddf6ef74c8af507bfdf0
 *  6                                      6 
 *  7 -- Accepted on 2024-04-29T19:12:55.0 . 
 *  . 00Z by 20240429T191255.msf_add_wsds_ . 
 *  . number.ts                            . 
 *  8                                      . 
 *  9 -- Extension "btree_gin", hash: 8833 7 -- Extension "btree_gin", hash: 8833
 *  . dd03dc128e186d2c560d248354fb         . dd03dc128e186d2c560d248354fb
 * 10 CREATE EXTENSION IF NOT EXISTS "btre 8 CREATE EXTENSION IF NOT EXISTS "btre
 * .. e_gin" CASCADE;                      . e_gin" CASCADE;
 * 11                                      9 
 * 
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 2/4 --- Text (8 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * 1339     "legacyData" jsonb             1337     "legacyData" jsonb
 * 1340 );                                 1338 );
 * 1341                                    1339 
 * 1342 -- Schema for "Users", hash: 9fdf3 1340 -- Schema for "Users", hash: e5995
 * .... 0c97e114fa7115c58cfab5497bf        .... cc92a16bff8cbb486e4100acd1a
 * 1343 CREATE TABLE "Users" (             1341 CREATE TABLE "Users" (
 * 1344     _id varchar(27) PRIMARY KEY,   1342     _id varchar(27) PRIMARY KEY,
 * 1345     "username" text,               1343     "username" text,
 * 
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 3/4 --- Text (8 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * 1411     "auto_subscribe_to_my_posts" b 1409     "auto_subscribe_to_my_posts" b
 * .... ool NOT NULL DEFAULT true,         .... ool NOT NULL DEFAULT true,
 * 1412     "auto_subscribe_to_my_comments 1410     "auto_subscribe_to_my_comments
 * .... " bool NOT NULL DEFAULT true,      .... " bool NOT NULL DEFAULT true,
 * 1413     "autoSubscribeAsOrganizer" boo 1411     "autoSubscribeAsOrganizer" boo
 * .... l NOT NULL DEFAULT true,           .... l NOT NULL DEFAULT true,
 * 1414     "notificationCommentsOnSubscri 1412     "notificationCommentsOnSubscri
 * .... bedPost" jsonb NOT NULL DEFAULT '{ .... bedPost" jsonb NOT NULL DEFAULT '{
 * .... "channel":"onsite","batchingFreque .... "channel":"both","batchingFrequenc
 * .... ncy":"realtime","timeOfDayGMT":12, .... y":"realtime","timeOfDayGMT":12,"d
 * .... "dayOfWeekGMT":"Monday"}' ::jsonb, .... ayOfWeekGMT":"Monday"}' ::jsonb,
 * 1415     "notificationShortformContent" 1413     "notificationShortformContent"
 * ....  jsonb NOT NULL DEFAULT '{"channel ....  jsonb NOT NULL DEFAULT '{"channel
 * .... ":"onsite","batchingFrequency":"re .... ":"onsite","batchingFrequency":"re
 * .... altime","timeOfDayGMT":12,"dayOfWe .... altime","timeOfDayGMT":12,"dayOfWe
 * .... ekGMT":"Monday"}' ::jsonb,         .... ekGMT":"Monday"}' ::jsonb,
 * 1416     "notificationRepliesToMyCommen 1414     "notificationRepliesToMyCommen
 * .... ts" jsonb NOT NULL DEFAULT '{"chan .... ts" jsonb NOT NULL DEFAULT '{"chan
 * .... nel":"onsite","batchingFrequency": .... nel":"both","batchingFrequency":"r
 * .... "realtime","timeOfDayGMT":12,"dayO .... ealtime","timeOfDayGMT":12,"dayOfW
 * .... fWeekGMT":"Monday"}' ::jsonb,      .... eekGMT":"Monday"}' ::jsonb,
 * 1417     "notificationRepliesToSubscrib 1415     "notificationRepliesToSubscrib
 * .... edComments" jsonb NOT NULL DEFAULT .... edComments" jsonb NOT NULL DEFAULT
 * ....  '{"channel":"onsite","batchingFre ....  '{"channel":"both","batchingFrequ
 * .... quency":"realtime","timeOfDayGMT": .... ency":"realtime","timeOfDayGMT":12
 * .... 12,"dayOfWeekGMT":"Monday"}' ::jso .... ,"dayOfWeekGMT":"Monday"}' ::jsonb
 * .... nb,                                .... ,
 * 1418     "notificationSubscribedUserPos 1416     "notificationSubscribedUserPos
 * .... t" jsonb NOT NULL DEFAULT '{"chann .... t" jsonb NOT NULL DEFAULT '{"chann
 * .... el":"onsite","batchingFrequency":" .... el":"both","batchingFrequency":"re
 * .... realtime","timeOfDayGMT":12,"dayOf .... altime","timeOfDayGMT":12,"dayOfWe
 * .... WeekGMT":"Monday"}' ::jsonb,       .... ekGMT":"Monday"}' ::jsonb,
 * 1419     "notificationSubscribedUserCom 1417     "notificationSubscribedUserCom
 * .... ment" jsonb NOT NULL DEFAULT '{"ch .... ment" jsonb NOT NULL DEFAULT '{"ch
 * .... annel":"onsite","batchingFrequency .... annel":"onsite","batchingFrequency
 * .... ":"realtime","timeOfDayGMT":12,"da .... ":"realtime","timeOfDayGMT":12,"da
 * .... yOfWeekGMT":"Monday"}' ::jsonb,    .... yOfWeekGMT":"Monday"}' ::jsonb,
 * 1420     "notificationPostsInGroups" js 1418     "notificationPostsInGroups" js
 * .... onb NOT NULL DEFAULT '{"channel":" .... onb NOT NULL DEFAULT '{"channel":"
 * .... both","batchingFrequency":"realtim .... both","batchingFrequency":"realtim
 * .... e","timeOfDayGMT":12,"dayOfWeekGMT .... e","timeOfDayGMT":12,"dayOfWeekGMT
 * .... ":"Monday"}' ::jsonb,              .... ":"Monday"}' ::jsonb,
 * 1421     "notificationSubscribedTagPost 1419     "notificationSubscribedTagPost
 *      " jsonb NOT NULL DEFAULT '{"channe      " jsonb NOT NULL DEFAULT '{"channe
 *      l":"onsite","batchingFrequency":"r      l":"onsite","batchingFrequency":"r
 *      ealtime","timeOfDayGMT":12,"dayOfW      ealtime","timeOfDayGMT":12,"dayOfW
 *      eekGMT":"Monday"}' ::jsonb,             eekGMT":"Monday"}' ::jsonb,
 * 
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 4/4 --- Text (8 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * 1430     "notificationCommentsOnDraft"  1428     "notificationCommentsOnDraft" 
 * .... jsonb NOT NULL DEFAULT '{"channel" .... jsonb NOT NULL DEFAULT '{"channel"
 * .... :"both","batchingFrequency":"realt .... :"both","batchingFrequency":"realt
 * .... ime","timeOfDayGMT":12,"dayOfWeekG .... ime","timeOfDayGMT":12,"dayOfWeekG
 * .... MT":"Monday"}' ::jsonb,            .... MT":"Monday"}' ::jsonb,
 * 1431     "notificationPostsNominatedRev 1429     "notificationPostsNominatedRev
 * .... iew" jsonb NOT NULL DEFAULT '{"cha .... iew" jsonb NOT NULL DEFAULT '{"cha
 * .... nnel":"both","batchingFrequency":" .... nnel":"both","batchingFrequency":"
 * .... realtime","timeOfDayGMT":12,"dayOf .... realtime","timeOfDayGMT":12,"dayOf
 * .... WeekGMT":"Monday"}' ::jsonb,       .... WeekGMT":"Monday"}' ::jsonb,
 * 1432     "notificationSubforumUnread" j 1430     "notificationSubforumUnread" j
 * .... sonb NOT NULL DEFAULT '{"channel": .... sonb NOT NULL DEFAULT '{"channel":
 * .... "onsite","batchingFrequency":"dail .... "onsite","batchingFrequency":"dail
 * .... y","timeOfDayGMT":12,"dayOfWeekGMT .... y","timeOfDayGMT":12,"dayOfWeekGMT
 * .... ":"Monday"}' ::jsonb,              .... ":"Monday"}' ::jsonb,
 * 1433     "notificationNewMention" jsonb 1431     "notificationNewMention" jsonb
 * ....  NOT NULL DEFAULT '{"channel":"ons ....  NOT NULL DEFAULT '{"channel":"bot
 * .... ite","batchingFrequency":"realtime .... h","batchingFrequency":"realtime",
 * .... ","timeOfDayGMT":12,"dayOfWeekGMT" .... "timeOfDayGMT":12,"dayOfWeekGMT":"
 * .... :"Monday"}' ::jsonb,               .... Monday"}' ::jsonb,
 * 1434     "notificationDialogueMessages" 1432     "notificationDialogueMessages"
 * ....  jsonb NOT NULL DEFAULT '{"channel ....  jsonb NOT NULL DEFAULT '{"channel
 * .... ":"both","batchingFrequency":"real .... ":"both","batchingFrequency":"real
 * .... time","timeOfDayGMT":12,"dayOfWeek .... time","timeOfDayGMT":12,"dayOfWeek
 * .... GMT":"Monday"}' ::jsonb,           .... GMT":"Monday"}' ::jsonb,
 * 1435     "notificationPublishedDialogue 1433     "notificationPublishedDialogue
 * .... Messages" jsonb NOT NULL DEFAULT ' .... Messages" jsonb NOT NULL DEFAULT '
 * .... {"channel":"onsite","batchingFrequ .... {"channel":"onsite","batchingFrequ
 * .... ency":"realtime","timeOfDayGMT":12 .... ency":"realtime","timeOfDayGMT":12
 * .... ,"dayOfWeekGMT":"Monday"}' ::jsonb .... ,"dayOfWeekGMT":"Monday"}' ::jsonb
 * .... ,                                  .... ,
 * 1436     "notificationAddedAsCoauthor"  1434     "notificationAddedAsCoauthor" 
 *      jsonb NOT NULL DEFAULT '{"channel"      jsonb NOT NULL DEFAULT '{"channel"
 *      :"both","batchingFrequency":"realt      :"both","batchingFrequency":"realt
 *      ime","timeOfDayGMT":12,"dayOfWeekG      ime","timeOfDayGMT":12,"dayOfWeekG
 *      MT":"Monday"}' ::jsonb,                 MT":"Monday"}' ::jsonb,
 * 
 * 
 * -------------------------------------------
 * (run `git diff --no-index schema/accepted_schema.sql schema/schema_to_accept.sql` to see this more clearly)
 *
 * - [ ] Write a migration to represent these changes
 * - [ ] Rename this file to something more readable
 * - [ ] Uncomment `acceptsSchemaHash` below
 * - [ ] Run `yarn acceptmigrations` to update the accepted schema hash (running makemigrations again will also do this)
 */
export const acceptsSchemaHash = "686739254a73ddf6ef74c8af507bfdf0";

export const up = async ({db}: MigrationContext) => {
  // just default value updates
}

export const down = async ({db}: MigrationContext) => {
  // just default value updates
}
